export const GET_BREADS_REQUEST = 'GET_BREADS_REQUEST';
export const GET_BREADS_SUCCESS = 'GET_BREADS_SUCCESS';
export const GET_BREADS_FAIL = 'GET_BREADS_FAIL';
export const SET_BREADS = 'SET_BREADS';